# .github/workflows/deploy-frontend.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend-new
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regenerate package-lock.json
        run: |
          if [ -f "package-lock.json" ]; then
            rm -f package-lock.json
          fi
          npm install --package-lock-only --no-audit
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd frontend-new
          npm install
      
      - name: Run Tests
        run: |
          cd frontend-new
          npm test
      
      - name: Build
        run: |
          cd frontend-new
          npm run build
      
      - name: Copy public files to dist
        run: |
          cd frontend-new
          cp -r public/* dist/
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend-new/dist
          branch: gh-pages
