# .github/workflows/deploy-frontend.yml
name: Build New Frontend

on:
  push:
    branches: [ main ]
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  actions: read

jobs:
  build-and-deploy-new-frontend:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: frontend-new
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Regenerate package-lock.json
        run: |
          cd frontend-new
          if [ -f "package-lock.json" ]; then
            rm -f package-lock.json
          fi
          npm install --package-lock-only --no-audit
          echo $("pwd")
          ls -ha
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          #cache: 'npm'
      
      - name: Install Dependencies
        run: |
          cd frontend-new
          npm install
      
      - name: Run Tests
        run: |
          cd frontend-new
          npm test
      
      - name: Build
        run: |
          cd frontend-new
          npm run build
          ls -ha
      
      # - name: Copy public files to dist
      #   run: |
      #     cp -r public/* dist/
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend-new/dist
          force_orphan: true
