# .github/workflows/mirror_repository.yml
name: Mirror GitHub Repository

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (format: owner/repo)'
        required: true
        default: 'dmarx/papers-feed'
      target_repo:
        description: 'Target repository (format: owner/repo)'
        required: true
        default: 'dmarx/papers-feed-dev'
      clear_target_labels:
        description: 'Clear all labels from issues in target repository'
        required: true
        type: boolean
        default: false
      issue_range_start:
        description: 'Starting issue number to copy (optional)'
        required: false
      issue_range_end:
        description: 'Ending issue number to copy (optional)'
        required: false

jobs:
  mirror-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone - only get the latest commit

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub fire loguru

      - name: Run mirroring script
        env:
          DEV_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/github_repo_mirror.py mirror \
            --source-repo=${{ github.event.inputs.source_repo }} \
            --target-repo=${{ github.event.inputs.target_repo }} \
            --clear-target-labels=${{ github.event.inputs.clear_target_labels }} \
            ${{ github.event.inputs.issue_range_start != '' && format('--issue-range-start={0}', github.event.inputs.issue_range_start) || '' }} \
            ${{ github.event.inputs.issue_range_end != '' && format('--issue-range-end={0}', github.event.inputs.issue_range_end) || '' }}
