# .github/workflows/paper-enrichment.yml

name: PDF Download and Enrichment

on:
  issues:
    types: [opened, reopened]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  

concurrency:
  group: ${{ github.repository }}-event-processing
  cancel-in-progress: false

jobs:
  download-pdfs:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'issues' || 
      (github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'feature-node'))
    permissions:
      contents: write
    outputs:
      has_changes: ${{ steps.commit.outputs.changes_detected }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install papers_feed
      
      - name: Download PDFs
        run: |
          python -m papers_feed.asset_manager download-pdfs
      
      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Download paper files"
          file_pattern: |
            data/papers/**

  convert-pdfs-to-markdown:
    runs-on: ubuntu-latest
    needs: download-pdfs
    if: github.event_name != 'issues' || needs.download-pdfs.outputs.has_changes == 'true'
    outputs:
      has_changes: ${{ steps.commit.outputs.changes_detected }}
    
    services:
      grobid:
        image: lfoppiano/grobid:latest-crf
        ports:
          - 8070:8070
        env:
          JAVA_OPTS: "-Xmx4g"
        volumes:
          - ${{ github.workspace }}:/opt/grobid/input
        options: "--init"
        
    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install llamero lxml requests
    
      - name: Process PDF
        env:
          GROBID_HOST: localhost
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8070/api/isalive > /dev/null; then
              echo "Grobid is ready!"
              break
            fi
            echo "Attempt $i: Service not ready yet, waiting..."
            sleep 10
          done
          python scripts/process_pdf.py generate_missing_conversions

      - name: Commit and Push Conversions
        id: commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          message: "Add tei xml's"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  process-enrichments:
    needs: convert-pdfs-to-markdown
    if: github.event_name != 'issues' || needs.convert-pdfs-to-markdown.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install llamero PyGithub duckduckgo-search
          
      - name: Process enrichments
        run: python scripts/process_enrichments.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
